@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 16 20:13:06 +0100 2019
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim CLOCK_DIVIDER_tb_behav -key {Behavioral:sim_1:Functional:CLOCK_DIVIDER_tb} -tclbatch CLOCK_DIVIDER_tb.tcl -log simulate.log"
call xsim  CLOCK_DIVIDER_tb_behav -key {Behavioral:sim_1:Functional:CLOCK_DIVIDER_tb} -tclbatch CLOCK_DIVIDER_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
