@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Jan 22 11:19:47 +0100 2020
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto af443ddf4ae44319a4b7a699d95b2f8e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot LAVADORA_TESTBENCH_behav xil_defaultlib.LAVADORA_TESTBENCH -log elaborate.log"
call xelab  -wto af443ddf4ae44319a4b7a699d95b2f8e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot LAVADORA_TESTBENCH_behav xil_defaultlib.LAVADORA_TESTBENCH -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
