@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 21 12:03:26 +0100 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim LAVADORA_TESTBENCH_behav -key {Behavioral:sim_1:Functional:LAVADORA_TESTBENCH} -tclbatch LAVADORA_TESTBENCH.tcl -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/DISPLAYS_TESTBENCH_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/FSM_CONTROL_TESTBENCH_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/slave_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/CLOCK_DIVIDER_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/Leds_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/TESTBENCH_GLOBAL_behav.wcfg -log simulate.log"
call xsim  LAVADORA_TESTBENCH_behav -key {Behavioral:sim_1:Functional:LAVADORA_TESTBENCH} -tclbatch LAVADORA_TESTBENCH.tcl -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/DISPLAYS_TESTBENCH_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/FSM_CONTROL_TESTBENCH_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/slave_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/CLOCK_DIVIDER_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/Leds_tb_behav.wcfg -view C:/Users/elena/OneDrive/Escritorio/LAVADORAv4/project_2/project_2.srcs/sim_1/imports/LavadoraSED/TESTBENCH_GLOBAL_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
